name: context
on: workflow_dispatch

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
    - name: github context
      run:g
    - name: check github context
      run: |
        echo ${{ github.repository }}
        echo ${{ github.event_name }}
